---
# tasks file for helm-packages
# Add prometheus chart repo
- name: Add kube-prometheus-stack chart repo
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: "https://prometheus-community.github.io/helm-charts"

- name: Create a k8s namespace
  kubernetes.core.k8s:
    name: monitoring
    api_version: v1
    kind: Namespace
    state: present

# Install kube prometheus stack
- name: Deploy kube-prometheus-stack
  kubernetes.core.helm:
    name: kube-prometheus-stack
    chart_ref: prometheus-community/kube-prometheus-stack
    chart_version: 62.5.0
    release_namespace: monitoring
    values: "{{ lookup('template', 'kube-prometheus-stack.yaml.j2') | from_yaml }}"

# Install open Search cluster with Dashborads
#helm repo add opensearch-operator https://opensearch-project.github.io/opensearch-k8s-operator/

- name: Add opensearch chart repo
  kubernetes.core.helm_repository:
    name: opensearch
    repo_url: "https://opensearch-project.github.io/helm-charts/"

# Install kube prometheus stack
- name: Deploy opensearch master
  kubernetes.core.helm:
    name: opensearch-master
    chart_ref: opensearch/opensearch
    chart_version: 2.23.2
    release_namespace: default
    values: "{{ lookup('file', 'master.yaml') | from_yaml }}"

- name: Deploy opensearch data
  kubernetes.core.helm:
    name: opensearch-data
    chart_ref: opensearch/opensearch
    chart_version: 2.23.2
    release_namespace: default
    values: "{{ lookup('file', 'data.yaml') | from_yaml }}"

- name: Deploy opensearch coordinator
  kubernetes.core.helm:
    name: opensearch-coordinator
    chart_ref: opensearch/opensearch
    chart_version: 2.23.2
    release_namespace: default
    values: "{{ lookup('file', 'client.yaml') | from_yaml }}"
  
  #Install tekton operator
- name: Deploy tekton operator
  ansible.builtin.command: kubectl apply -f https://storage.googleapis.com/tekton-releases/operator/latest/release.yaml

  #profiles: lite , all, basic
- name: Deploy tekton operator
  ansible.builtin.command: kubectl apply -f https://raw.githubusercontent.com/tektoncd/operator/main/config/crs/kubernetes/config/all/operator_v1alpha1_config_cr.yaml