---
- name: Make sure we have the necessary yum packages available for selinux
  ansible.builtin.yum:
    name:
      - libselinux-python3
      - libsemanage-python3
      - python3-policycoreutils
      - policycoreutils
      - policycoreutils-python-utils
    state: present
  vars:
    py_suffix: '{{ "3" if ansible_python.version.major == 3 else "" }}'