---
- name: Make config directory
  become: true
  file:
    path: "{{ kubernetes_kubeadm_kubelet_config_file_path | dirname }}"
    state: directory

- name: Merge Kubeadm template
  become: true
  template:
    src: "kubeadm-cluster-config.j2"
    dest: "{{ kubernetes_kubeadm_kubelet_config_file_path }}"

- name: Pre Kubeadm reset kubeadm 
  become: true
  command: >
    kubeadm reset --force      

- name: Initialize Kubernetes control plane with kubeadm init
  become: true
  command: >
    kubeadm init 
    --config {{ kubernetes_kubeadm_kubelet_config_file_path }}
    --ignore-preflight-errors=all
  register: kubeadmin_init
  
    
- name: Kubeadm reset kubeadm 
  become: true
  command: >
    kubeadm reset --force  