---
- name: redhat variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Credentials Redhat
  include_vars: vault.yml

- include_tasks: attach-subscription-manager.yml
- include_tasks: ip-tables-bridge.yml

- include_tasks: firewall-disable.yml
- include_tasks: base-k8s-package-installation.yml


- include_tasks: cluster-cp-init.yml
- include_tasks: cp-init-master-replicas.yml 
#- include_tasks: detach-subscription-manager.yml