---
- name: procps-ng installation
  package: 
    name: "{{ procps_package }}"
    state: present
  when: >
    ansible_distribution != 'Debian'

- name: iptables bridged traffic
  sysctl:
    name: "{{ item }}"
    value: '1'
    state: present
  loop:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables
  when: >
    ansible_distribution != 'Debian'  
       