---
- name: Extract RPM TAR GZ
  ansible.builtin.unarchive:
    src: "/home/amit/allpackages.tgz"
    dest: "/home/amit"
    remote_src: yes
  become: true  

- name: Extract Images TAR GZ
  ansible.builtin.unarchive:
    src: "/home/amit/allimages.tgz"
    dest: "/home/amit"
    remote_src: yes
  become: true

# check if its lb machine and packages exist
- name: Check if the directory exists
  stat:
    path: "{{ basedir }}/lb/alllb.tgz"
  register: file_data

# Extract if exists loadbalancer
- name: Extract RPM TAR GZ for loadbalancer
  ansible.builtin.unarchive:
    src: "/home/amit/alllb.tgz"
    dest: "/home/amit"
    remote_src: yes
  become: true
  when: file_data.stat.exists

- name: Delete original files
  ansible.builtin.file:
     path: "{{basedir}}/allpackages.tgz"
     state: absent
  become: true

- name: Delete original files
  ansible.builtin.file:
     path: "{{basedir}}/allimages.tgz"
     state: absent
  become: true